wandb_version: 1

model_name:
  desc: null
  value: movie_predictor
optimizer:
  desc: null
  value: adam
num_epochs:
  desc: null
  value: 30
lr:
  desc: null
  value: 0.001
model_ext:
  desc: null
  value: pth
api_key:
  desc: null
  value: ab7faf2607ec6880e3da76705fc88da0948d8d38
project_name:
  desc: null
  value: movie-predictor
run_name:
  desc: null
  value: peach-haze-1
next_run_name:
  desc: null
  value: peach-haze-002
_wandb:
  desc: null
  value:
    python_version: 3.11.4
    cli_version: 0.17.6
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1723363475
    t:
      1:
      - 1
      - 5
      - 53
      - 55
      2:
      - 1
      - 5
      - 53
      - 55
      3:
      - 13
      - 14
      - 15
      - 16
      - 23
      4: 3.11.4
      5: 0.17.6
      8:
      - 5
      13: linux-x86_64
